/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_worktips_worktipsnet_WorktipsnetVPN_VPNInfo */

#ifndef _Included_network_worktips_worktipsnet_WorktipsnetVPN_VPNInfo
#define _Included_network_worktips_worktipsnet_WorktipsnetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
