/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_worktips_worktipsnet_WorktipsnetDaemon */

#ifndef _Included_network_worktips_worktipsnet_WorktipsnetDaemon
#define _Included_network_worktips_worktipsnet_WorktipsnetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_Obtain(JNIEnv *, jclass);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_Free(JNIEnv *, jclass, jobject);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    Configure
   * Signature: (Lnetwork/worktips/worktipsnet/WorktipsnetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_Configure(JNIEnv *, jobject, jobject);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_Mainloop(JNIEnv *, jobject);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_IsRunning(JNIEnv *, jobject);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_Stop(JNIEnv *, jobject);

  /*
   * Class:     network_worktips_worktipsnet_WorktipsnetDaemon
   * Method:    InjectVPN
   * Signature: (Lnetwork/worktips/worktipsnet/WorktipsnetVPN;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_worktips_worktipsnet_WorktipsnetDaemon_InjectVPN(JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
