#!/bin/sh
echo "Running preinstall" > /tmp/worktipsnet_preinstall.log
if [ ! -d "$HOME/.worktipsnet" ]
then
  mkdir $HOME/.worktipsnet >> /tmp/worktipsnet_preinstall.log
fi
find $HOME/.worktipsnet >> /tmp/worktipsnet_preinstall.log
exit 0 # all good
