apiVersion: apps/v1
kind: Deployment
metadata:
  name: worktips-deployment
  labels:
    app: worktips-svc-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worktips-svc-node
  template:
    metadata:
      labels:
        app: worktips-svc-node
    spec:
      containers:
      - name: worktips-svc-node
        image: jaaff/worktips-svc-kubernetes
        ports:
          - protocol: TCP
            port: 22022
            targetPort: 22022
          - protocol: TCP
            port: 22023
            targetPort: 22023
          - protocol: UDP
            port: 1090
            targetPort: 1090
          