#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/worktipsnet || echo "failed to setcap worktipsnet"
adduser --quiet --system --home /var/lib/worktipsnet debian-worktipsnet || echo "debian-worktipsnet user not added"
